apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      run: hello-kubernetes
  template:
    metadata:
      labels:
        run: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: hello-kubernetes:latest
        ports:
        - containerPort: 80

